
[Settings]
ID = "3a9a8242-ede7-4486-932a-0694b9562437"

# Settings in the [build] context are global and are applied to all contexts unless otherwise overridden by more specific contexts.  

[build]
  # This is the directory to change to before starting a build.
  base    = "weather-app/"
  # NOTE: This is where we will look for package.json/.nvmrc/etc, not root.
  # This is the directory that you are publishing from (relative to root of your repo)
  publish = "weather-app/build"
  # This will be your default build command
  command = "yarn build"